version: "3.8"
services:
  db:
    image: postgres:15
    container_name: openplantprotocols-db
    environment:
      POSTGRES_USER: openpp
      POSTGRES_PASSWORD: openpppass
      POSTGRES_DB: openplantprotocols
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
